[versions]
agp = "8.3.2"

# Test
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.5.1"

# AndroidX
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.9.0"
constraintlayout = "2.1.4"

# ðŸ”¹ ROOM
room = "2.6.1"

# ðŸ”¹ SPLASH SCREEN (ðŸ†• EKLENDÄ°)
coreSplashscreen = "1.0.1"


[libraries]

# ðŸ”¹ Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# ðŸ”¹ AndroidX
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

# ðŸ”¹ ROOM
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# ðŸ”¹ SPLASH SCREEN (ðŸ†• EKLENDÄ°)
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
